### ISSUE TITLE
Valid status from sigma repo is test as well as testing

### ISSUE THREAD

**Issue by devinbfergy** [bradleyjkemp/sigmafmt#5]
Looks like test needs to be added to the list in valid_status.go

**Comment by devinbfergy** [comment]
This is based on rules from the main sigma repo. I was testing to make sure your repo would still work on those rules. :)

**Comment by bradleyjkemp** [comment]
Hmm tricky. This is another case where two bits of the Sigma spec disagree :/

The text says "test" is fine (https://github.com/SigmaHQ/sigma/wiki/Specification#status-optional) but the YAML schema says it needs to be "testing" https://github.com/SigmaHQ/sigma/wiki/Specification#rx-yaml

Usually it's the python code that wins the argument but I'm not sure where this field might actually get used by `sigmac`?

**Comment by devinbfergy** [comment]
#6 I created a pull request with the above. 

I think that it would be nice if testing got auto formatted to test if found. Gonna work on a PR for that as well if you don't mind.

**Comment by devinbfergy** [comment]
I created a PR on the sigma repo to fix the specification to match the wiki page as well. Seeing as it follows the code in the filter.py. https://github.com/SigmaHQ/sigma/pull/2739

**Comment by devinbfergy** [comment]
That PR got pulled in so the issue with the specification being weird should be fixed now. Hopefully that helps make the case for changing the linter check.

**Comment by devinbfergy** [comment]
The wiki didn't auto update from the actual spec file. https://github.com/SigmaHQ/sigma/issues/2743
